name = "survey-form"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database binding for Pages Functions
[[d1_databases]]
binding = "DB"
database_name = "survey-db"
database_id = "5029b843-01cc-424e-b57b-94028a0d9c1e"

# Environment variables
[vars]
ADMIN_PASSWORD = "3939889"
